version: '3.8'
volumes:
  postgres-data:
services:
  api:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    depends_on:
      - db
    environment:
      - PORT=5000
      - DATABASE_LOGIN_URL=postgresql://postgres:secret@db/postgres
      - ENVIRONMENT=development
    ports:
      - '8080:5000'
    # volumes:
    #   - ./src:/app/src:cached # <--- This will map ./api to /root/app inside the container.
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432