version: '3.8'
volumes:
  postgres-data:
services:
  api:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    environment:
      - PORT=5000
      - DATABASE_LOGIN_URL=postgresql://postgres:secret@db/postgres
    ports:
      - '5001:5000'
    volumes:
      - ./app:/app/app:cached # <--- This will map ./api to /root/app inside the container.
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432