name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  tag: ${{ secrets.DOCKERHUB_USERNAME }}/health-backend:latest
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:

  get-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with: 
          github_token: ${{ env.token }}
          fetch_all_tags: true
      - run: if [ ${{ steps.tag_version.outputs.tag != '' }} ] then; echo "tag=${{ env.tag }},${{ secrets.DOCKERHUB_USERNAME }}/health-backend:${{ steps.tag_version.outputs.tag }}" >> $GITHUB_ENV; fi
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}

  docker:
    runs-on: ubuntu-latest
    needs: get-tag
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.tag }}
